[package]
name = "trackforge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "trackforge"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.18.1", features = ["extension-module"], optional = true }

[features]
default = []
python = ["dep:pyo3"]
